# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='createdate',
            field=models.DateField(default='2016-11-23'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='memo',
            field=models.TextField(default='xxxx'),
        ),
    ]
